---
title: "Correlation of RNA-seq and CUT&RUN results"
output: html_notebook
---

# Libraries
```{r}
library(tidyverse)
library(plyranges)
```

# Functions

# Read RNA
```{r}
res_housing_cs_combat <- read_tsv("~/repos/rnaseq_social_isolation/data_output/combat/res_housing_cs_combat.tsv")
```

```{r}
library(org.Dm.eg.db)
library(GenomicFeatures)
library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)


gene_id_map <- clusterProfiler::bitr(fromType = "ENSEMBL",toType = "SYMBOL",geneID = res_housing_cs_combat$geneid,OrgDb = org.Dm.eg.db)


res_housing_cs_combat <- res_housing_cs_combat[res_housing_cs_combat$geneid %in% gene_id_map$ENSEMBL,]

res_housing_cs_combat <- left_join(res_housing_cs_combat,gene_id_map,by = c("geneid" = "SYMBOL"))

promoters_dm6 <- promoters(genes(TxDb.Dmelanogaster.UCSC.dm6.ensGene),upstream = 1,downstream = 1)



res_housing_cs_combat <- res_housing_cs_combat[res_housing_cs_combat$geneid %in% names(promoters_dm6),]


promoters_dm6 <- promoters_dm6[res_housing_cs_combat$geneid]

elementMetadata(promoters_dm6) <- DataFrame(res_housing_cs_combat)

```


# Read CUT&RUN
```{r}
cutnrun_h3k27ac <- makeGRangesFromDataFrame(readRDS("../data_output/diffbind_cutnrun/results_cutnrun_H3K27ac_macs2_peaks_union_deseq_ashr.tsv"),keep.extra.columns = TRUE)

cutnrun_h3k4me3 <-  makeGRangesFromDataFrame(readRDS("../data_output/diffbind_cutnrun/results_cutnrun_H3K4me3_macs2_peaks_union_deseq_ashr.tsv") ,keep.extra.columns = TRUE)
cutnrun_igg <-  makeGRangesFromDataFrame(readRDS("../data_output/diffbind_cutnrun/results_cutnrun_IgG_macs2_peaks_union_deseq_ashr.tsv"),keep.extra.columns = TRUE)
cutnrun_rnapolii <-  makeGRangesFromDataFrame(readRDS("../data_output/diffbind_cutnrun/results_cutnrun_RNAPolII_macs2_peaks_union_deseq_ashr.tsv"),keep.extra.columns = TRUE)

```

# Join tables


```{r}
seqlevels(promoters_dm6) <- str_remove(seqlevels(promoters_dm6),"chr")
colnames(elementMetadata(promoters_dm6)) <- paste0(colnames(elementMetadata(promoters_dm6)),"_rnaseq")

```

```{r}
cutnrun_h3k27ac_rna <- plyranges::join_overlap_left_within(promoters_dm6,cutnrun_h3k27ac)
cutnrun_h3k4me3_rna <- plyranges::join_overlap_left_within(promoters_dm6,cutnrun_h3k4me3)
cutnrun_igg_rna <- plyranges::join_overlap_left_within(promoters_dm6,cutnrun_igg)
cutnrun_rnapolii_rna <- plyranges::join_overlap_left_within(promoters_dm6,cutnrun_rnapolii)
```


# Plots

```{r}

options(scipen = 999)
as.data.frame(cutnrun_h3k27ac_rna) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K27ac")

as.data.frame(cutnrun_h3k4me3_rna) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K4me3")

as.data.frame(cutnrun_igg_rna) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("IgG")

as.data.frame(cutnrun_rnapolii_rna) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("RNAPolII")
```


```{r}
options(scipen = 999)
as.data.frame(cutnrun_h3k27ac_rna) %>%
  filter(padj_rnaseq < 0.05) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K27ac")

as.data.frame(cutnrun_h3k4me3_rna) %>%
  filter(padj_rnaseq < 0.05) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K4me3")

as.data.frame(cutnrun_igg_rna) %>%
  filter(padj_rnaseq < 0.05) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("IgG")

as.data.frame(cutnrun_rnapolii_rna) %>%
  filter(padj_rnaseq < 0.05) %>%
  ggplot(aes(log2FoldChange_rnaseq, log2FoldChange)) +
  geom_point(size = 0.2) +
  ggpubr::stat_cor() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("RNAPolII")
```


```{r}
cutnrun_rnapolii %>%
  as_data_frame() %>%
  ggplot(aes(baseMean, log2FoldChange, color = padj < 0.05)) +
  geom_point() +
  scale_x_log10() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("RNAPolII")

cutnrun_h3k27ac %>%
  as_data_frame() %>%
  ggplot(aes(baseMean, log2FoldChange, color = padj < 0.05)) +
  geom_point() +
  scale_x_log10() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K27ac")

cutnrun_h3k4me3 %>%
  as_data_frame() %>%
  ggplot(aes(baseMean, log2FoldChange, color = padj < 0.05)) +
  geom_point() +
  scale_x_log10() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("H3K4me3")

cutnrun_igg %>%
  as_data_frame() %>%
  ggplot(aes(baseMean, log2FoldChange, color = padj < 0.05)) +
  geom_point() +
  scale_x_log10() +
  theme_light() +
  theme(aspect.ratio = 1) +
  ggtitle("IgG")

```

```{r}

```

